version: '2'
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-drupal
    ports:
      - "8040:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-sites:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=test1234
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-sites:
  drupal-themes:
  drupal-sites:
  drupal-data:
